public class calc{
    integer a,b,c;
    public void add(){
        a=8;
        b=2;
        c=a+b;
        System.debug(c);
    }
    public void sub(){
        a=8;
        b=2;
        c=a-b;
        System.debug(c);
    }
    public void mul(){
        a=8;
        b=2;
        c=a*b;
        System.debug(c);
    }
    public void div(){
        a=8;
        b=2;
        c=a/b;
        System.debug(c);
    }
}