public class MethodTypes {
    public static String str='How Are You...';
    public static Integer i=10;
    public static void M(){
        System.debug('Welcome');
    }
    public static void M1(){
        System.debug(5000);
    }
    public String a='Welcome to CRM';
    public Integer b=80000;
    public Void Method(){
        System.Debug('This is non-static Function');
    }
    public Void Method1(){
        System.Debug('This is non-static Function  2');
    }
}